name: shopping_allocation_planner
publish_to: none
environment:
  sdk: ^3.12.0
dependencies:
  crypto: ^3.0.6
  googleapis_auth: ^2.0.0
  http: ^1.0.0
  kitchensync:
    path: ../..
dev_dependencies:
  flutter_test:
    sdk: flutter
